home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.Home, name="index"),
    path("Home/", views.Home, name="index"),
    path('about/', views.AboutUs, name='about'),
    path('project/', views.project, name='project'),
    path('quote/', views.quote, name='quote'),
    path('contact/', views.contact, name='contact'),
    path('service/', views.service, name='service'),
    path('team/', views.team, name='team'),
    path('ereur/', views.ereur, name='ereur'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('feature/', views.feature, name='feature'),
]

project/urls.py
from django.contrib import admin
from django.urls    import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('connect_as/', include('authentication.urls')),
    path('dashboard_super/', include('supervisor.urls')),
    path('dashboard_client/', include('client.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supervisor/urls.py
from django.urls    import path
from .              import views


app_name = 'supervisor'

urlpatterns = [
    path('', views.index, name='dashboard_super'),
        #######* CRUD OF CLIENT  ##########
    path('list_client/', views.list_clients, name="list_client"),
    path('add_client/', views.add_client, name="add_client"),
    path('update_client/<int:pk>/', views.update_client, name="update_client"),
    path('delete_client/<int:pk>/', views.delete_client, name="delete_client"),

        #######* CRUD OF Project  ##########
    path('project_list/', views.list_project, name='list_project'),
    path('add_project/', views.add_project, name= 'add_project'),
    path('update_project/<int:project_id>', views.update_project, name='update_project'),
    path('delete_project/<int:pk>', views.delete_project, name='delete_project'),
    path('add_parcelle/', views.parcelle_create, name = 'add_parcelle'),
    path('get_parcelles_for_project/', views.get_parcelles_for_project, name='get_parcelles_for_project'),

        #######* Node Related  ##########
    path('add_node/', views.node_create, name='add_node'),
    path('get_parcelles_with_nodes_for_project/', views.get_parcelles_with_nodes_for_project, name='get_parcelles_with_nodes_for_project'),
    path('get_project_details/<int:project_id>/', views.get_project_details, name='get_project_details'),
    path('update_parcels_nodes/', views.update_parcels_nodes, name='update_parcels_nodes'),
]

supervisor/models/parcelle.py
from django.contrib.gis.db      import models
from supervisor.models.project  import Project

class Parcelle(models.Model):
    name = models.CharField(max_length=30)
    polygon = models.PolygonField(null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True, related_name='parcelle')

    def __str__(self):
        if self.project:
            return f'Parcelle of project: {self.project.name}'
        else:
            return 'Parcelle with no project assigned for now'

supervisor/views/clients.py
from django.contrib.auth.models         import User
from django.http                        import HttpResponse, JsonResponse
from django.shortcuts                   import render, redirect, get_object_or_404
from django.contrib.auth.decorators     import login_required
from django.contrib                     import messages
from authentication.decorators          import supervisor_required
from supervisor.forms                   import ClientForm
from client.models                      import Client
from django.core.exceptions             import ValidationError
import json


@login_required(login_url='supervisor_login')
@supervisor_required
def list_clients(request):
    clients = Client.objects.all()
    form = ClientForm()
    return render(request, 'website/clients/list_client.html', {'clients': clients, 'form': form})


@login_required(login_url='supervisor_login')
@supervisor_required
def add_client(request):
    show_modal = False
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                client = form.save(commit=False)
                client.save()
                form.save_m2m()
                messages.success(request, 'Client added successfully.')
                return redirect('supervisor:list_client')
            except ValidationError as e:
                show_modal = True
                form.add_error(None, e)
        else:
            show_modal = True
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ClientForm()
    clients = Client.objects.all()
    return render(request, 'website/clients/list_client.html', {'form': form, 'clients': clients, 'show_modal': show_modal})



@login_required(login_url='supervisor_login')
@supervisor_required
def update_client(request, pk):
    client = get_object_or_404(Client, pk=pk)
    user = get_object_or_404(User, pk=client.user.pk) 

    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            client = form.save(commit=False)
            # Update the user associated with the client
            user.username = form.cleaned_data.get('username')
            user.email = form.cleaned_data.get('email')
            if form.cleaned_data.get('password'):
                user.set_password(form.cleaned_data.get('password'))
            user.save()
            client.user = user
            client.save()
            messages.success(request, 'Client updated successfully.')

            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                client_data = {
                    'pk': client.pk,
                    'firstName': client.firstName,
                    'lastName': client.lastName,
                    'username': user.username,
                    'email': user.email,
                    'phone': client.phone,
                    'image': client.image.url if client.image else ''
                }
                return JsonResponse({'success': True, 'client': client_data})
            return redirect('supervisor:list_client')
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': form.errors})
            messages.error(request, 'Please correct the errors below.')
    else:
        client_data = {
            'firstName': client.firstName,
            'lastName': client.lastName,
            'email': client.email,
            'phone': client.phone,
            'username': client.username,
            'image': client.image.url if client.image else ''
        }
        return HttpResponse(json.dumps(client_data), content_type="application/json")
    
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse({'success': False, 'message': 'Invalid request method'})
    return render(request, 'website/clients/list_client.html', {'form': form, 'clients': Client.objects.all()})



@login_required(login_url='supervisor_login')
@supervisor_required
def delete_client(request, pk):
    client = get_object_or_404(Client, pk=pk)
    client.delete()
    return redirect('supervisor:list_client')

supervisor/views/index.py
from django.shortcuts               import render
from django.contrib.auth.decorators import login_required
from authentication.decorators      import supervisor_required



@login_required(login_url='supervisor_login')
@supervisor_required
def index(request):
    return render(request, 'website/index.html', {})

supervisor/views/project.py
import json
from supervisor.models.node         import Node
from django.db.models               import Count, Value
from django.contrib.gis.geos        import Polygon
from django.contrib                 import messages
from django.http                    import JsonResponse
from django.shortcuts               import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from authentication.decorators      import supervisor_required
from django.db.models.functions     import Concat
from django.contrib.gis.geos        import Point
from supervisor.models.parcelle     import Parcelle 
from supervisor.models.project      import Project
from supervisor.forms               import ProjectForm
from supervisor.forms               import ParcelleForm
from supervisor.forms               import NodeForm



@login_required(login_url='supervisor_login')
@supervisor_required
def list_project(request):
    client_id = request.GET.get('client_id')
    projects_by_client = Project.objects.annotate(
        full_name=Concat('client__firstName', Value(' '), 'client__lastName')
    ).values('full_name', 'client_id').annotate(count=Count('client')).order_by('full_name')
    if client_id:
        projects = Project.objects.filter(client_id=client_id)  
    else:
        projects = Project.objects.all()
    form = ProjectForm()
    return render(request, 'website/project.html', {
        'projects_by_client': projects_by_client,
        'projects': projects,
        'form': form
    })

@login_required(login_url='supervisor_login')
@supervisor_required
def add_project(request):
    form = ProjectForm(request.POST or None, request.FILES or None)
    data = {'latitude': None, 'longitude': None}
    client_name = None
    project_name = None

    if request.method == 'POST':
        if form.is_valid():
            project = form.save(commit=False)
            project_name = project.name
            client_name = f"{project.client.firstName} {project.client.lastName}"

            #! Vérifiez si un projet avec le même nom et la même ville existe déjà
            existing_project = Project.objects.filter(name=project_name, city=project.city).first()

            if existing_project:
                existing_project.descp = form.cleaned_data.get('descp', existing_project.descp)
                existing_project.date_debut = form.cleaned_data.get('date_debut', existing_project.date_debut)
                existing_project.date_fin = form.cleaned_data.get('date_fin', existing_project.date_fin)
                existing_project.client = form.cleaned_data.get('client', existing_project.client)
                existing_project.save()
                messages.success(request, 'Project updated successfully.')
                project = existing_project
            else:
                project.save()
                form.save_m2m()
                messages.success(request, 'Project added successfully.')
            
            latitude = float(project.city.latitude)
            longitude = float(project.city.longitude)
            data = {'latitude': latitude, 'longitude': longitude}
            request.session['project_added'] = True  
            request.session['map_data'] = data
            parcelle_form = ParcelleForm(initial={'project': project})
            node_form = NodeForm()
            return render(request, 'website/project.html', {
                'form': form,
                'show_map_modal': True,
                'data': data,
                'parcelle_form': parcelle_form,
                'node_form': node_form,
                'project_name': project_name,
                'client_name': client_name
            })
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ProjectForm()

    if 'map_data' in request.session:
        data = request.session['map_data']

    show_map_modal = request.session.get('project_added', False)
    response = render(request, 'website/project.html', {
        'form': form,
        'show_map_modal': show_map_modal,
        'data': data,
        'project_name': project_name,
        'client_name': client_name
    })

    request.session['project_added'] = False
    request.session['map_data'] = None

    return response


@login_required(login_url='supervisor_login')
@supervisor_required
def get_project_details(request, project_id):
    try:
        project = Project.objects.get(pk=project_id)
        data = {
            'project_name': project.name,
            'client_name': f"{project.client.firstName} {project.client.lastName}",
            'latitude': project.city.latitude,
            'longitude': project.city.longitude,
        }
        return JsonResponse(data)
    except Project.DoesNotExist:
        return JsonResponse({'error': 'Project not found'}, status=404)



@login_required(login_url='supervisor_login')
@supervisor_required
def delete_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    project.delete()
    messages.success(request, 'Project deleted successfully.')
    return redirect('supervisor:list_project')




@login_required(login_url='supervisor_login')
@supervisor_required
def update_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            messages.success(request, 'Project updated successfully.')
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                project_data = {
                    'pk': project.pk,
                    'name': project.name,
                    'description': project.description,
                    'start_date': project.start_date,
                    'end_date': project.end_date,
                }
                return JsonResponse({'success': True, 'project': project_data})
            return redirect('supervisor:list_project')
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': form.errors})
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ProjectForm(instance=project)

    return render(request, 'website/project.html', {
        'form': form,
        'update': True,
        'project': project,
    })



@login_required(login_url='supervisor_login')
@supervisor_required
def parcelle_create(request):
    if request.method == 'POST':
        form = ParcelleForm(request.POST)
        if form.is_valid():
            coordinates_data = request.POST.get('coordinates')
            parcelle_id = request.POST.get('parcelle_id', None)
            try:
                coordinates = json.loads(coordinates_data)
                if coordinates[0] != coordinates[-1]:
                    coordinates.append(coordinates[0])
                polygon = Polygon(coordinates)

                if parcelle_id:
                    parcelle = get_object_or_404(Parcelle, id=parcelle_id)
                    parcelle.polygon = polygon
                    parcelle.save()
                    message = 'Polygon updated successfully.'
                else:
                    existing_parcelles = Parcelle.objects.all()
                    for existing_parcelle in existing_parcelles:
                        if polygon.equals_exact(existing_parcelle.polygon, tolerance=1e-9):
                            return JsonResponse({'error': {'name': [{'message': 'A parcel with these coordinates already exists.', 'code': 'unique'}]}}, status=400)

                    parcelle = form.save(commit=False)
                    parcelle.polygon = polygon
                    parcelle.save()
                    message = 'Polygon added successfully.'

                parcels = [{
                    'id': p.id,
                    'name': p.name,
                    'coordinates': list(p.polygon.coords[0])
                } for p in Parcelle.objects.filter(project=parcelle.project)]

                return JsonResponse({'message': message, 'parcels': parcels}, status=200)
            except (ValueError, TypeError) as e:
                return JsonResponse({'error': {'coordinates': [{'message': 'Invalid coordinates format.', 'code': 'invalid'}]}}, status=400)
        else:
            errors = form.errors.get_json_data()
            return JsonResponse({'error': errors}, status=400)
    else:
        form = ParcelleForm()
        projects = Project.objects.all()
        project_data = []

        for project in projects:
            parcelles = Parcelle.objects.filter(project=project)
            project_parcelles = [{
                'id': parcelle.id,
                'name': parcelle.name,
                'coordinates': list(parcelle.polygon.coords[0])
            } for parcelle in parcelles]
            project_data.append({
                'project': {
                    'id': project.id,
                    'name': project.name,
                    'latitude': project.city.latitude,
                    'longitude': project.city.longitude
                },
                'parcelles': project_parcelles
            })

        return render(request, 'website/project.html', {
            'form': form,
            'project_data': project_data, 
        })



@login_required(login_url='supervisor_login')
@supervisor_required
def get_parcelles_for_project(request):
    project_id = request.GET.get('project_id')
    if project_id:
        parcelles = Parcelle.objects.filter(project_id=project_id)
        parcelle_data = [{
            'id': parcelle.id,
            'name': parcelle.name,
            'coordinates': list(parcelle.polygon.coords[0])
        } for parcelle in parcelles]
        return JsonResponse({'parcelles': parcelle_data}, status=200)
    else:

supervisor/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SFG - Together We Protect Our Farme!</title>
    <link rel="icon" type="image/png" href="{% static 'assets/img/logo4.png' %}">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">


    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">


    <!-- Leaflet CSS and JS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" 
    integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" 
    integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css" />

    <script src="{% static 'js/index.js' %}"></script>

</head>
<body data-showmapmodal="{{ show_map_modal|yesno:'true,false' }}" data-list-url="{% url 'supervisor:list_project' %}">
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar  navbar-light">
                <a href="{% url 'supervisor:dashboard_super' %}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary">SUPERVISOR</h3>
                </a>
                <div class="navbar-nav w-100">
                    <a href="{% url 'supervisor:dashboard_super' %}" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <a href="{% url 'supervisor:list_client' %}" class="nav-item nav-link"><i class="fa fa-th-list me-2"></i>Customer list</a>
                    <a href="{% url 'supervisor:list_project' %}" class="nav-item nav-link"><i class="fa fa-th-list me-2"></i>Project List</a>
                    <div style="position: fixed; bottom: 20px;">
                        <a href="{% url 'logout_supervisor' %}" class="nav-item nav-link"><i class="fa fa-sign-out-alt me-2"></i>Logout</a>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        
        {% block content %}
        {% endblock %}



        <!-- Back to Top -->
        <a href="{% url 'supervisor:dashboard_super' %}" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
</body>
</html>